//
// Created by vanessa on 7/2/22.
//

#ifndef INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_QPS_EVALUATOR_RETRIEVER_PARENT_RETRIEVER_H_
#define INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_QPS_EVALUATOR_RETRIEVER_PARENT_RETRIEVER_H_

class parent_retriever {

};

#endif //INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_QPS_EVALUATOR_RETRIEVER_PARENT_RETRIEVER_H_
