name: clang-format Check

on:
  push:
    branches-ignore:
      - production
    paths:
      - 'Team31/Code31/src/spa/src/**'
  pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Link .clang-format in root
      run: "ln -s $GITHUB_WORKSPACE/Team31/Code31/.clang-format $GITHUB_WORKSPACE/"

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '12'
        check-path: 'Team31/Code31/src/spa/src'
        fallback-style: 'Google'
