name: clang-format Check

on:
  push:
    branches-ignore:
      - production
    paths:
      - 'Team31/Code31/src/spa/src/**'
  pull_request:

jobs:
  dup_check:
    name: Check for repeat
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1

  formatting-check:
    name: Formatting Check
    needs: dup_check
    if: ${{ needs.dup_check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Link .clang-format in root
      run: "ln -s $GITHUB_WORKSPACE/Team31/Code31/.clang-format $GITHUB_WORKSPACE/"

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '12'
        check-path: 'Team31/Code31/src/spa/src'
        fallback-style: 'Google'
