name: CMake Builds

on:
  push:
    branches-ignore:
      - production
    paths:
      - 'Team31/Code31/**'
  pull_request:

env:
    BUILD_TYPE: Release
    CMAKE_BUILD_PARALLEL_LEVEL: 6

jobs:
  build:
    name: CMake
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.temp }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.temp }}/build
        run: cmake $GITHUB_WORKSPACE/Team31/Code31/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{ runner.temp }}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Run unit tests
        working-directory: Team31/Tests31
        shell: bash
        run: |
             if [ "$RUNNER_OS" == "Windows" ]; then
                 $RUNNER_TEMP/build/src/unit_testing/$BUILD_TYPE/unit_testing.exe
             else
                 $RUNNER_TEMP/build/src/unit_testing/unit_testing
             fi

      - name: Run integration tests
        working-directory: Team31/Tests31
        shell: bash
        run: |
             if [ "$RUNNER_OS" == "Windows" ]; then
                 $RUNNER_TEMP/build/src/integration_testing/$BUILD_TYPE/integration_testing.exe
             else
                 $RUNNER_TEMP/build/src/integration_testing/integration_testing
             fi
