//
// Created by vanessa on 5/2/22.
//

#ifndef INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_PQLENUMS_H_
#define INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_PQLENUMS_H_

namespace PQLEnums {

    enum TargetType {
        ALL, ASSIGN, IF, WHILE, PROCEDURE, READ, CALL, CONTAINER, PRINT, VARIABLE, CONSTANT
    };

};

#endif //INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_PQLENUMS_H_
