//
// Created by vanessa on 5/2/22.
//

#ifndef INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_ENUMSPQL_H_
#define INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_ENUMSPQL_H_

namespace EnumsPQL {

    enum TargetType {
        ALL, ASSIGN, IF, WHILE, PROCEDURE, READ, CALL, CONTAINER, PRINT, VARIABLE, CONSTANT
    };

    enum GroupType {
        NO_SYNONYMS, NO_TARGET, WITH_TARGET
    };

};

#endif //INC_21S2_CP_SPA_TEAM_31_TEAM31_CODE31_SRC_SPA_SRC_PQLEVALUATOR_ENUMSPQL_H_
